name: "Antarraksha GAASI Survivability Gate"
description: "Blocks CI/CD if AI agent fails GAASI survivability evaluation"

inputs:
  agent_payload_path:
    description: "Path to GAASI agent payload JSON"
    required: true

runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash

    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
